version: '3.8'

services:
  markitdown-server:
    # Replace YOUR_USERNAME with your actual Docker Hub username
    image: YOUR_USERNAME/markitdown-server:latest
    container_name: markitdown-server
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount a directory for file uploads if needed
      - ./uploads:/app/uploads:ro
      # Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - markitdown-network

networks:
  markitdown-network:
    driver: bridge

# Optional: Add volumes for data persistence
volumes:
  markitdown-data:
    driver: local 